# Generated by Django 5.0.6 on 2024-06-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(unique=True)),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("poster_id", models.BigIntegerField(unique=True)),
                ("firstname", models.CharField(blank=True, max_length=50, null=True)),
                ("lastname", models.CharField(blank=True, max_length=50, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("group_name", models.CharField(max_length=10)),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "customers",
                "managed": False,
            },
        ),
    ]
