# Generated by Django 5.0.6 on 2024-06-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField(blank=True, null=True)),
                ("grade", models.IntegerField()),
                ("type", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "reviews",
                "managed": False,
            },
        ),
    ]
