# Generated by Django 5.0.6 on 2024-06-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("monday", models.CharField(blank=True, max_length=200)),
                ("tuesday", models.CharField(blank=True, max_length=200)),
                ("wednesday", models.CharField(blank=True, max_length=200)),
                ("thursday", models.CharField(blank=True, max_length=200)),
                ("friday", models.CharField(blank=True, max_length=200)),
                ("saturday", models.CharField(blank=True, max_length=200)),
                ("sunday", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
