# Generated by Django 5.0.6 on 2024-06-20 08:02

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift_schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="friday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="monday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="name",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="saturday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="sunday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="thursday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="tuesday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="wednesday",
        ),
        migrations.AddField(
            model_name="shift",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="shift",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="shift",
            name="worker",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
