# Generated by Django 5.0.6 on 2024-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift_schedule", "0002_remove_shift_friday_remove_shift_monday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="week_day",
            field=models.IntegerField(default=1),
        ),
    ]
