# Generated by Django 5.0.6 on 2024-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift_schedule", "0003_shift_week_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="start_time",
        ),
        migrations.AddField(
            model_name="shift",
            name="Shift",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shift",
            name="week_day",
            field=models.IntegerField(default=0),
        ),
    ]
