# Generated by Django 5.0.6 on 2024-06-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "shift_schedule",
            "0004_remove_shift_end_time_remove_shift_start_time_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="shift",
            old_name="Shift",
            new_name="shift",
        ),
    ]
