# Generated by Django 5.0.6 on 2024-06-20 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift_schedule", "0005_rename_shift_shift_shift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="week_day",
        ),
        migrations.AddField(
            model_name="shift",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
