# Generated by Django 5.0.6 on 2024-06-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shift_schedule", "0006_remove_shift_week_day_shift_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("date", "shift")},
        ),
    ]
